version: "3.5"

services:
  webrtc:
    build:
      context: .
      args:
        WEBRTC_VERSION: "77"
        WEBRTC_COMMIT: "ad73985e75684cb4ac4dadb9d3d86ad0d66612a0"
    image: shiguredo/windows-webrtc:m75-159c16f3
